### ISSUE TITLE
An unknown proto fault has occured => [Expected number type for integral field. ... poke-api/request_builder.rb:90:in `initialize']

### ISSUE THREAD

**Issue by nik736** [nabeelamjad/poke-api#13]
Hello again,

I have tried to integrate the "release_pokemon" RPC call. The output of inspect is the following:

`#<Poke::API::Client @auth=#<Poke::API::Auth::GOOGLE:0x007fef17898088> @reqs=[{:RELEASE_POKEMON=>{:pokemon_id=>"1234567890"}}] @lat=0 @lng=0 @alt=0>`

(I changed the pokemon_id)

The error is the following:

> Poke::API::Errors::UnknownProtoFault (An unknown proto fault has occured => [Expected number type for integral field. @ /xxx/ruby-2.3.0/bundler/gems/poke-api-3223d8bf915b/lib/poke-api/request_builder.rb:90:in `initialize']):
>   app/controllers/pokemon_controller.rb:18:in`transfer'

Line 18 is simply the `call = client.call` call.

I am not sure if I used the correct pokemon id, I guessed that this is the `id` I get from the regular `get_inventory` call. Is this correct or where do I get the pokemon id from?

Thanks for any help!

**Comment by xssc** [comment]
It seems your `:pokemon_id=>"1234567890"` is a string (Note the quotes around the number) but the proto expects a number. How are you calling `release_pokemon`?. You should be passing `pokemon_id` as a number

**Comment by nabeelamjad** [comment]
Yes that is correct (with the exception that you're passing in a string), here's an example:

``` ruby
{:pokemon_data=>
 {:id=>5997233404021068431,
  :pokemon_id=>:KOFFING,
  :cp=>263,
  :stamina=>32,
  :stamina_max=>32,
  :move_1=>:ACID_FAST,
  :move_2=>:SLUDGE_BOMB,
...}
}

[19] pry(main)> client.release_pokemon(pokemon_id: 5997233404021068431)
=> [{:RELEASE_POKEMON=>{:pokemon_id=>5997233404021068431}}]
[20] pry(main)> client.call
[2016-07-27T20:11:22+00:00]: DEBUG > Poke::API::RequestBuilder --: [+] Creating new request
[2016-07-27T20:11:22+00:00]: INFO  > Poke::API::RequestBuilder --: [+] Adding 'RELEASE_POKEMON' to RPC request with arguments
[2016-07-27T20:11:22+00:00]: DEBUG > Poke::API::RequestBuilder --: [+] RELEASE_POKEMON: {:pokemon_id=>5997233404021068431}
[2016-07-27T20:11:22+00:00]: INFO  > Poke::API::RequestBuilder --: [+] Executing RPC request
[2016-07-27T20:11:23+00:00]: INFO  > Poke::API::Response       --: [+] Decoding Main RPC responses
[2016-07-27T20:11:23+00:00]: INFO  > Poke::API::Response       --: [+] Decoding Sub RPC responses
[2016-07-27T20:11:23+00:00]: DEBUG > Poke::API::Response       --: [+] Returned RPC response
{:RELEASE_POKEMON=>{:result=>:SUCCESS, :candy_awarded=>1}}
[2016-07-27T20:11:23+00:00]: INFO  > Poke::API::Client         --: [+] Cleaning up RPC requests
=> #<Poke::API::Response:0x00000002f1e580 @request=[{:RELEASE_POKEMON=>{:pokemon_id=>5997233404021068431}}], @response={:RELEASE_POKEMON=>{:result=>:SUCCESS, :candy_awarded=>1}}>
```

**Comment by nik736** [comment]
Ah, thanks! It's working now :-)

**Comment by nabeelamjad** [comment]
Another helpful thing to look out for is [**this line**](https://github.com/nabeelamjad/poke-api/blob/master/lib/poke-api/POGOProtos/Networking/Requests/Messages/ReleasePokemonMessage.rb#L8) as it indicates `:fixed64` as a value required (which always is an integer). 

Here's a table format of values possible for [protocol buffers](https://developers.google.com/protocol-buffers/docs/proto):

| prototype |
| --- |
| double |
| float |
| int32 |
| int64 |
| uint32 |
| uint64 |
| sint32 |
| sint64 |
| fixed32 |
| fixed64 |
| sfixed32 |
| sfixed64 |
| bool |
| string |
| bytes |
