### ISSUE TITLE
Heroku deployment login issue

### ISSUE THREAD

**Issue by dphuang2** [nabeelamjad/poke-api#21]
Logging in with the API locally on my computer yields no errors. But when I try to use it on Heroku's servers I get this error. 

```
Loading production environment (Rails 5.0.0)
irb(main):001:0> client = Poke::API::Client.new
=> #<Poke::API::Client @auth= @reqs=[] @lat=0 @lng=0 @alt=0>
irb(main):002:0> client.login("xxx","xxx","ptc")
[2016-07-31T04:49:03+00:00]: INFO  > Poke::API::Client         --: [+] Logging in user: xxx
[2016-07-31T04:49:04+00:00]: INFO  > Poke::API::Client         --: [+] Login with PTC Successful
[2016-07-31T04:49:04+00:00]: INFO  > Poke::API::RequestBuilder --: [+] Adding 'GET_PLAYER' to RPC request
[2016-07-31T04:49:04+00:00]: INFO  > Poke::API::RequestBuilder --: [+] Adding 'GET_HATCHED_EGGS' to RPC request
[2016-07-31T04:49:04+00:00]: INFO  > Poke::API::RequestBuilder --: [+] Adding 'GET_INVENTORY' to RPC request
[2016-07-31T04:49:04+00:00]: INFO  > Poke::API::RequestBuilder --: [+] Adding 'CHECK_AWARDED_BADGES' to RPC request
[2016-07-31T04:49:04+00:00]: INFO  > Poke::API::RequestBuilder --: [+] Adding 'DOWNLOAD_SETTINGS' to RPC request with arguments
[2016-07-31T04:49:04+00:00]: INFO  > Poke::API::RequestBuilder --: [+] Executing RPC request
[2016-07-31T04:49:04+00:00]: INFO  > Poke::API::Response       --: [+] Decoding Main RPC responses
[2016-07-31T04:49:04+00:00]: INFO  > Poke::API::Client         --: [+] Cleaning up RPC requests
Poke::API::Errors::UnknownProtoFault: An unknown proto fault has occured => [Error occurred during parsing: Unmatched ENDGROUP tag. @ /app/vendor/bundle/ruby/2.2.0/bundler/gems/poke-api-85ee2d01f869/lib/poke-api/response.rb:14:in `decode']
    from /app/vendor/bundle/ruby/2.2.0/bundler/gems/poke-api-85ee2d01f869/lib/poke-api/client.rb:39:in `rescue in call'
    from /app/vendor/bundle/ruby/2.2.0/bundler/gems/poke-api-85ee2d01f869/lib/poke-api/client.rb:43:in `call'
    from /app/vendor/bundle/ruby/2.2.0/bundler/gems/poke-api-85ee2d01f869/lib/poke-api/client.rb:70:in `fetch_endpoint'
    from /app/vendor/bundle/ruby/2.2.0/bundler/gems/poke-api-85ee2d01f869/lib/poke-api/client.rb:29:in `login'
    from (irb):2
    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/commands/console.rb:65:in `start'
    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/commands/console_helper.rb:9:in `start'
    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:78:in `console'
    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
    from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
    from bin/rails:9:in `require'
    from bin/rails:9:in `<main>'
irb(main):003:0>
```

To replicate this error you have to make a Rails project and client.login through Heroku console (accessed by "heroku run console"). I don't know if this is a problem with the API, my development environment, or with heroku itself. But I have tried to figure this out for a while and have gotten nowhere. If anyone has any insight to Rails deployment to Heroku and possible culprits that would be great.

I am using Ruby 2.2.4 and Rails 5.0 and have tried deploying with Ruby 2.2.4 to no avail.

**Comment by nabeelamjad** [comment]
Apparently they banned Amazon EC2 servers, since Heroku runs on those it wouldn't work anymore (since it won't give you a response back).

It makes sense in all honesty from their point of view if they want to crack down on people using the API, however, legitimate users could be playing Pokemon GO using a VPN hosted in the cloud...

**Comment by dphuang2** [comment]
RIP, I see all the buzz about it now...
