### ISSUE TITLE
Getting unknown type: size_t input_size

### ISSUE THREAD

**Issue by krzkrzkrz** [nabeelamjad/poke-api#40]
Currently getting:

```
/Users/foo/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/poke-go-api-0.1.7/lib/poke-api/client.rb:44:in `rescue in call': An unknown proto fault has occured => [unknown type: size_t input_size @ /Users/foo/.rbenv/versions/2.2.5/lib/ruby/2.2.0/fiddle/cparser.rb:171:in `parse_ctype'] (Poke::API::Errors::UnknownProtoFault)
        from /Users/foo/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/poke-go-api-0.1.7/lib/poke-api/client.rb:48:in `call'
```

This just suddenly appeared. Im guessing due to PoGo API update?

**Comment by nabeelamjad** [comment]
Try updating Ruby to 2.3
